/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorStoreRouteImport } from './routes/vendor.store'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorReviewsRouteImport } from './routes/vendor.reviews'
import { Route as VendorReturnsRouteImport } from './routes/vendor.returns'
import { Route as VendorReportsRouteImport } from './routes/vendor.reports'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as VendorPoliciesRouteImport } from './routes/vendor.policies'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorOnboardingRouteImport } from './routes/vendor.onboarding'
import { Route as VendorInventoryRouteImport } from './routes/vendor.inventory'
import { Route as VendorEarningsRouteImport } from './routes/vendor.earnings'
import { Route as VendorDiagnosticsRouteImport } from './routes/vendor.diagnostics'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin.diagnostics'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as VendorProductsIndexRouteImport } from './routes/vendor.products.index'
import { Route as VendorProductsPendingRouteImport } from './routes/vendor.products.pending'
import { Route as VendorProductsNewRouteImport } from './routes/vendor.products.new'
import { Route as VendorAdminProductsRouteImport } from './routes/vendor.admin.products'
import { Route as VendorAdminOrdersRouteImport } from './routes/vendor.admin.orders'
import { Route as VendorAdminApprovalsRouteImport } from './routes/vendor.admin.approvals'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorStoreRoute = VendorStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => VendorRoute,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorReviewsRoute = VendorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => VendorRoute,
} as any)
const VendorReturnsRoute = VendorReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => VendorRoute,
} as any)
const VendorReportsRoute = VendorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VendorRoute,
} as any)
const VendorPoliciesRoute = VendorPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOnboardingRoute = VendorOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => VendorRoute,
} as any)
const VendorInventoryRoute = VendorInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => VendorRoute,
} as any)
const VendorEarningsRoute = VendorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorDiagnosticsRoute = VendorDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => VendorRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProductsIndexRoute = VendorProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsPendingRoute = VendorProductsPendingRouteImport.update({
  id: '/products/pending',
  path: '/products/pending',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsNewRoute = VendorProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAdminProductsRoute = VendorAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAdminOrdersRoute = VendorAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAdminApprovalsRoute = VendorAdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => VendorRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/vendor': typeof VendorRouteWithChildren
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/vendor/diagnostics': typeof VendorDiagnosticsRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/onboarding': typeof VendorOnboardingRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/policies': typeof VendorPoliciesRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/returns': typeof VendorReturnsRoute
  '/vendor/reviews': typeof VendorReviewsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/store': typeof VendorStoreRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/vendor/admin/approvals': typeof VendorAdminApprovalsRoute
  '/vendor/admin/orders': typeof VendorAdminOrdersRoute
  '/vendor/admin/products': typeof VendorAdminProductsRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/vendor/products/pending': typeof VendorProductsPendingRoute
  '/vendor/products/': typeof VendorProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/vendor/diagnostics': typeof VendorDiagnosticsRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/onboarding': typeof VendorOnboardingRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/policies': typeof VendorPoliciesRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/returns': typeof VendorReturnsRoute
  '/vendor/reviews': typeof VendorReviewsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/store': typeof VendorStoreRoute
  '/admin': typeof AdminIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/vendor/admin/approvals': typeof VendorAdminApprovalsRoute
  '/vendor/admin/orders': typeof VendorAdminOrdersRoute
  '/vendor/admin/products': typeof VendorAdminProductsRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/vendor/products/pending': typeof VendorProductsPendingRoute
  '/vendor/products': typeof VendorProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/vendor': typeof VendorRouteWithChildren
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/vendor/diagnostics': typeof VendorDiagnosticsRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/inventory': typeof VendorInventoryRoute
  '/vendor/onboarding': typeof VendorOnboardingRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/policies': typeof VendorPoliciesRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/vendor/reports': typeof VendorReportsRoute
  '/vendor/returns': typeof VendorReturnsRoute
  '/vendor/reviews': typeof VendorReviewsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/vendor/store': typeof VendorStoreRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/vendor/admin/approvals': typeof VendorAdminApprovalsRoute
  '/vendor/admin/orders': typeof VendorAdminOrdersRoute
  '/vendor/admin/products': typeof VendorAdminProductsRoute
  '/vendor/products/new': typeof VendorProductsNewRoute
  '/vendor/products/pending': typeof VendorProductsPendingRoute
  '/vendor/products/': typeof VendorProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/vendor'
    | '/account/orders'
    | '/admin/approvals'
    | '/admin/diagnostics'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/settings'
    | '/checkout/success'
    | '/vendor/diagnostics'
    | '/vendor/earnings'
    | '/vendor/inventory'
    | '/vendor/onboarding'
    | '/vendor/orders'
    | '/vendor/policies'
    | '/vendor/profile'
    | '/vendor/reports'
    | '/vendor/returns'
    | '/vendor/reviews'
    | '/vendor/settings'
    | '/vendor/store'
    | '/admin/'
    | '/vendor/'
    | '/account/orders/$orderId'
    | '/api/public/paystack-webhook'
    | '/vendor/admin/approvals'
    | '/vendor/admin/orders'
    | '/vendor/admin/products'
    | '/vendor/products/new'
    | '/vendor/products/pending'
    | '/vendor/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/account/orders'
    | '/admin/approvals'
    | '/admin/diagnostics'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/settings'
    | '/checkout/success'
    | '/vendor/diagnostics'
    | '/vendor/earnings'
    | '/vendor/inventory'
    | '/vendor/onboarding'
    | '/vendor/orders'
    | '/vendor/policies'
    | '/vendor/profile'
    | '/vendor/reports'
    | '/vendor/returns'
    | '/vendor/reviews'
    | '/vendor/settings'
    | '/vendor/store'
    | '/admin'
    | '/vendor'
    | '/account/orders/$orderId'
    | '/api/public/paystack-webhook'
    | '/vendor/admin/approvals'
    | '/vendor/admin/orders'
    | '/vendor/admin/products'
    | '/vendor/products/new'
    | '/vendor/products/pending'
    | '/vendor/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/vendor'
    | '/account/orders'
    | '/admin/approvals'
    | '/admin/diagnostics'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/settings'
    | '/checkout/success'
    | '/vendor/diagnostics'
    | '/vendor/earnings'
    | '/vendor/inventory'
    | '/vendor/onboarding'
    | '/vendor/orders'
    | '/vendor/policies'
    | '/vendor/profile'
    | '/vendor/reports'
    | '/vendor/returns'
    | '/vendor/reviews'
    | '/vendor/settings'
    | '/vendor/store'
    | '/admin/'
    | '/vendor/'
    | '/account/orders/$orderId'
    | '/api/public/paystack-webhook'
    | '/vendor/admin/approvals'
    | '/vendor/admin/orders'
    | '/vendor/admin/products'
    | '/vendor/products/new'
    | '/vendor/products/pending'
    | '/vendor/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VendorRoute: typeof VendorRouteWithChildren
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/store': {
      id: '/vendor/store'
      path: '/store'
      fullPath: '/vendor/store'
      preLoaderRoute: typeof VendorStoreRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/reviews': {
      id: '/vendor/reviews'
      path: '/reviews'
      fullPath: '/vendor/reviews'
      preLoaderRoute: typeof VendorReviewsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/returns': {
      id: '/vendor/returns'
      path: '/returns'
      fullPath: '/vendor/returns'
      preLoaderRoute: typeof VendorReturnsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/reports': {
      id: '/vendor/reports'
      path: '/reports'
      fullPath: '/vendor/reports'
      preLoaderRoute: typeof VendorReportsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/policies': {
      id: '/vendor/policies'
      path: '/policies'
      fullPath: '/vendor/policies'
      preLoaderRoute: typeof VendorPoliciesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/onboarding': {
      id: '/vendor/onboarding'
      path: '/onboarding'
      fullPath: '/vendor/onboarding'
      preLoaderRoute: typeof VendorOnboardingRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/inventory': {
      id: '/vendor/inventory'
      path: '/inventory'
      fullPath: '/vendor/inventory'
      preLoaderRoute: typeof VendorInventoryRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/earnings': {
      id: '/vendor/earnings'
      path: '/earnings'
      fullPath: '/vendor/earnings'
      preLoaderRoute: typeof VendorEarningsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/diagnostics': {
      id: '/vendor/diagnostics'
      path: '/diagnostics'
      fullPath: '/vendor/diagnostics'
      preLoaderRoute: typeof VendorDiagnosticsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/products/': {
      id: '/vendor/products/'
      path: '/products'
      fullPath: '/vendor/products/'
      preLoaderRoute: typeof VendorProductsIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products/pending': {
      id: '/vendor/products/pending'
      path: '/products/pending'
      fullPath: '/vendor/products/pending'
      preLoaderRoute: typeof VendorProductsPendingRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products/new': {
      id: '/vendor/products/new'
      path: '/products/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof VendorProductsNewRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/admin/products': {
      id: '/vendor/admin/products'
      path: '/admin/products'
      fullPath: '/vendor/admin/products'
      preLoaderRoute: typeof VendorAdminProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/admin/orders': {
      id: '/vendor/admin/orders'
      path: '/admin/orders'
      fullPath: '/vendor/admin/orders'
      preLoaderRoute: typeof VendorAdminOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/admin/approvals': {
      id: '/vendor/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/vendor/admin/approvals'
      preLoaderRoute: typeof VendorAdminApprovalsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface VendorRouteChildren {
  VendorDiagnosticsRoute: typeof VendorDiagnosticsRoute
  VendorEarningsRoute: typeof VendorEarningsRoute
  VendorInventoryRoute: typeof VendorInventoryRoute
  VendorOnboardingRoute: typeof VendorOnboardingRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorPoliciesRoute: typeof VendorPoliciesRoute
  VendorProfileRoute: typeof VendorProfileRoute
  VendorReportsRoute: typeof VendorReportsRoute
  VendorReturnsRoute: typeof VendorReturnsRoute
  VendorReviewsRoute: typeof VendorReviewsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorStoreRoute: typeof VendorStoreRoute
  VendorIndexRoute: typeof VendorIndexRoute
  VendorAdminApprovalsRoute: typeof VendorAdminApprovalsRoute
  VendorAdminOrdersRoute: typeof VendorAdminOrdersRoute
  VendorAdminProductsRoute: typeof VendorAdminProductsRoute
  VendorProductsNewRoute: typeof VendorProductsNewRoute
  VendorProductsPendingRoute: typeof VendorProductsPendingRoute
  VendorProductsIndexRoute: typeof VendorProductsIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorDiagnosticsRoute: VendorDiagnosticsRoute,
  VendorEarningsRoute: VendorEarningsRoute,
  VendorInventoryRoute: VendorInventoryRoute,
  VendorOnboardingRoute: VendorOnboardingRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorPoliciesRoute: VendorPoliciesRoute,
  VendorProfileRoute: VendorProfileRoute,
  VendorReportsRoute: VendorReportsRoute,
  VendorReturnsRoute: VendorReturnsRoute,
  VendorReviewsRoute: VendorReviewsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorStoreRoute: VendorStoreRoute,
  VendorIndexRoute: VendorIndexRoute,
  VendorAdminApprovalsRoute: VendorAdminApprovalsRoute,
  VendorAdminOrdersRoute: VendorAdminOrdersRoute,
  VendorAdminProductsRoute: VendorAdminProductsRoute,
  VendorProductsNewRoute: VendorProductsNewRoute,
  VendorProductsPendingRoute: VendorProductsPendingRoute,
  VendorProductsIndexRoute: VendorProductsIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VendorRoute: VendorRouteWithChildren,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
